# This is a basic workflow to generate build
name: "pre-release"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the current branch
on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
  workflow_dispatch:
    inputs:
      comment:
        description: 'Add comment for manual workflow execution.'
        required: false
        default: 'Manual execution of Github workflow.'

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    
    steps:
      # ...
      - name: "Generate App Build"
        run: |
          echo "Started generating build."
      
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}
          path: splunk_maxmind_db_auto_update
            
      - name: "Generate Build"
        run: |
          cd splunk_maxmind_db_auto_update
          rm -rf .git
          rm -rf .github
          rm -rf backup_app_icons
          rm -f .gitignore
          cd ..
          find splunk_maxmind_db_auto_update -type f -exec chmod 644 '{}' \;
          find splunk_maxmind_db_auto_update -type d -exec chmod 755 '{}' \;
          tar -czf splunk_maxmind_db_auto_update.tgz splunk_maxmind_db_auto_update
          
      - uses: actions/upload-artifact@v2
        with:
          name: "build"
          path: |
            splunk_maxmind_db_auto_update.tgz
      
      - uses: splunk/appinspect-cli-action@v1
        with:
          app_path: 'splunk_maxmind_db_auto_update.tgz'
          result_file: 'app-appinspect-mode-test.json'
          

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: "app_inspect_reports"
          path: |
            app-appinspect-mode-test.json
