name: "Build and Local App Inspect"

on:
  pull_request:
  workflow_dispatch:

jobs:
  on_pr:
    name: "Build and Local App Inspect"
    runs-on: "ubuntu-latest"

    steps:
      - uses: VatsalJagani/splunk-app-action@v7
        env:
          SPLUNK_APP_ACTION_1: "rm -rf backup_app_icons"
          SPLUNK_APP_ACTION_2: "rm -f .gitignore"
          SPLUNK_APP_ACTION_3: "rm -rf Note_*"
          SPLUNK_APP_ACTION_4: "rm -rf images"
        with:
          app_dir: "."
          to_make_permission_changes: true
          local_app_inspect: true
          python_requirements_file: "lib/requirements.txt"
          is_remove_not_allowed_executables_from_lib: true
